### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by RuiZhangCSU** [MengGuo/P_MAS_TG#1]
Is your P_MAS_TG compiled in Linux?

**Comment by MengGuo** [comment]
hey, thanks for your email

there is no need to compile. It is python-based.

Once you have dependent packages, i.e., networkx, ply and the ltl2ba
executable file, you should be able to run the example without problem.

please let me know how it goes,
/Meng

**Comment by RuiZhangCSU** [comment]
Hello, Mr. Guo. I am so excited to receive your reply. I am sorry to reply you so late. I am from Central South University in Changsha, China and will be a doctor in September, 2016. I am finding out some interesting research and I am interested in yours very much. Nowadays I am reading your paper and thesis. I also want to understand your software and simulation results. As what you said, I download your software and corresponding dependent packages, but still there exists some problem. The python I used is installed in the Windows. I think that the problem is the ltl2ba which is compiled in linux. and I want your help. Thank you very much! The probelm I encountered is as follows:
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

> > >  RESTART: E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\Example.py 

Traceback (most recent call last):
  File "E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\Example.py", line 63, in <module>
    NAO_planner = ltl_planner(NAO_model, hard_spec, soft_spec)
  File "E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\planner.py", line 10, in **init**
    buchi = mission_to_buchi(hard_spec, soft_spec)
  File "E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\buchi.py", line 26, in mission_to_buchi
    buchi = buchi_from_ltl(hard_spec,'hard_buchi')
  File "E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\buchi.py", line 11, in buchi_from_ltl
    promela_string = run_ltl2ba(formula)
  File "E:\formal method\symbolic planning\Meng Guo\P_MAS_TG-master\ltl2ba.py", line 13, in run_ltl2ba
    raw_output = check_output([ltl2ba, "-f", "%s" % formula])
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, _popenargs, *_kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 不是有效的 Win32

**Comment by MengGuo** [comment]
Hey,

thanks for your email.

It seems that the only problem is the 'ltl2ba' executable file. Since these
two executable file provided are complied until gcc in unix, not for
windows, you need to download the source from
http://www.lsv.ens-cachan.fr/~gastin/ltl2ba/download.php and compile it
under the complier you used for windows (probably visual studio...not
sure).

After that, you copy the executable file to your working folder, you should
be able to run it. Let me know!

/Meng

**Comment by RuiZhangCSU** [comment]
hello, Mr. Guo, thanks for your reply.
now I can run Example.py in Ubuntu and I can obtain the corresponding datas without figures. But for the other cases, the error that is without module P_MAS_TG.ts would appear. what is the P_MAS_TG.ts . Very sorry to trouble you. Could you give me your email, or I hope that you can send your suggestions to my mailbox, ruizhangCSU@163.com. Thank you very much! 
With best wishes!

**Comment by MengGuo** [comment]
hey,

great you can run the example.

P_MAS_TG.ts is the class for finite transition systems. I didn't add
visualization for the graphs as you can easily look it up for networkx
graphs.

you can reach me by guomeng3@gmail.com if you want.

/Meng
