### ISSUE TITLE
There is no .mat file?

### ISSUE THREAD

**Issue by LiuZesensengsheng** [MengGuo/P_MAS_TG#3]
Mr. Guo:
    Hello! I'm Liu and I am focusing on your previous works recently. I add the PYTHONPATH and run example in to_matlab successifuly. But I can't find any file with the prefix .mat so I can't put them in visual. What's more, there is no file named To_MAS_TG.motion so I can't run the file in the multi-  successifully. I also notice that it's a project 5 years ago so maybe its data has been lost? 
Beast wished.

**Comment by MengGuo** [comment]
hello, you mean [this file](https://github.com/MengGuo/P_MAS_TG/blob/master/Intro/Examples/to_matlab/square_world.py)?

the `.mat` file is generated for the product automata. I added that function as many colleagues want to use the generated product automata with their own algorithms implemented in MatLAB. 

Based on [these lines](https://github.com/MengGuo/P_MAS_TG/blob/master/Intro/Examples/to_matlab/square_world.py#L142-L158), they are saved under `data/*.dat`. So you may want to check the `data` folder and the visualization is in `figures` folder. 

Let me know.

**Comment by MengGuo** [comment]
@LiuZesensengsheng where is the `agents_planner.py` script which you mentioned with a `contract_time` not defined?
